[package]
name = "b"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ioc = { workspace = true }
linkme = { workspace = true }
env_logger = "0.11.8"
log = "0.4.28"